#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap		12

bspc config focused_border_color "#74C7F6"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#rules
bscp rule -r "*"
bspc rule -a mpv state=fullscreen
bspc rule -a Emacs state=tiled
bspc rule -a firefox:Places state=floating rectangle=800x600+560+240
bspc rule -a firefox:Toolkit state=floating sticky=on

# Terminate already running instances
processes=("picom" "polybar" "sxhkd" "dunst")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done

# Launch polybar
polybar &

# Launch sxhkd
sxhkd &

# Launch dunst notification daemon
dunst &

# Launch picom 
picom &

# Set wallpaper
feh --bg-fill --randomize ~/.config/bspwm/wallpapers/
