# window rules

windowrule=width:400,height:250,title:Picture in picture
windowrule=offsetx:100,offsety:100,title:Picture in picture
windowrule=isfloating:1,title:Picture in picture
windowrule=isglobal:1,title:Picture in picture
windowrule=isoverlay:1,title:Picture in picture
windowrule=isopensilent:1,title:Picture in picture
windowrule=istagsilent:1,title:Picture in picture
